name: qsm pipeline test
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test_install:
    runs-on: ubuntu-latest
    steps:
    - name: Install node
      uses: actions/setup-node@v2.5.2
      with:
        node-version: v12.13.0
    - uses: actions/checkout@v3
    - name: Test setup.bash
      run: |
        /bin/bash setup.bash
        
